-- Create the database (run this first if the database doesn't exist)
-- CREATE DATABASE midterm_db;

-- Create the students table
CREATE TABLE IF NOT EXISTS students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    course VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create an index on email for faster lookups
CREATE INDEX IF NOT EXISTS idx_student_email ON students(email);

-- Sample data (optional)
-- INSERT INTO students (name, email, course) VALUES
-- ('John Doe', 'john@example.com', 'Computer Science'),
-- ('Jane Smith', 'jane@example.com', 'Mathematics'),
-- ('Bob Johnson', 'bob@example.com', 'Physics');
